'''
python3 简单教学教程
Tensorflow 中的optimizer 分了很多种,最基础的是 GradientDescentOptimizer,还有像 AdamOptimizer 等等,具体的可以在这个网址里找到:https://www.tensorflow.org/versions/r.... 
对于各种对学习效率的优化原理可以在这里找到(英文):http://cs231n.github.io/neural-networ...
'''
